# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-19 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30, verbose_name='Pizza')),
                ('opis', models.TextField(blank=True, help_text='Opis Pizzy')),
                ('rozmiar', models.CharField(choices=[('L', 'du\u017ca'), ('M', '\u015brednia'), ('S', 'ma\u0142a')], default='L', max_length=1)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data', models.DateField(auto_now_add=True, verbose_name='dodano')),
            ],
            options={
                'verbose_name_plural': 'pizze',
            },
        ),
        migrations.CreateModel(
            name='Skladnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField(verbose_name='odpowied\u017a')),
                ('jarski', models.BooleanField(default=False, help_text='Zaznacz, je\u017celi sk\u0142adnik jest odpowiedni dla wegetarian', verbose_name='jarski?')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skladniki', to='pizza.Pizza')),
            ],
            options={
                'verbose_name': 'sk\u0142adnik',
                'verbose_name_plural': 'sk\u0142adniki',
            },
        ),
    ]
